security:
    encoders:
        App\Entity\Enseignant:
            algorithm: bcrypt
            cost: 14

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Enseignant
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^(?!/api) # every route but /api
            provider: app_user_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\EnseignantAuthenticator
            logout:
                path: app_logout
                # target: app_any_route
            # switch_user: true
    access_control:
         - { path: ^/(en|fr|es)/etudiant, roles: ROLE_ADMIN }
         - { path: ^/(en|fr|es)/evaluation, roles: ROLE_USER }
         - { path: ^/(en|fr|es)/statut, roles: ROLE_USER }
         - { path: ^/(en|fr|es)/partie, roles: ROLE_USER }
         - { path: ^/(en|fr|es)/statistiques, roles: ROLE_USER }
         - { path: ^/(en|fr|es)/tutoriels, roles: ROLE_USER }